### ISSUE TITLE
Can we avoid the dependency on TiddlyChromeSaver.js?

### ISSUE THREAD

**Issue by Jermolene** [Arlen22/tiddly-chrome-app#1] opened 2015-07-21 07:11 UTC
I'm not familiar with the capabilities of Chrome extensions, so I wondered if it were possible to refactor communication between TW and the extension so that we can reuse the existing TiddlyFox saver module:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/savers/tiddlyfox.js

Instead of using messages, communication is handled through the DOM. Is that possible in Chrome?

**Comment by Arlen22** [comment] 2015-07-21 12:00
Yes, I believe it is possible. 

The only drawback is that Chrome Apps don't really have any way of asking "Are you sure" before closing if there are unsaved changes (like a tiddler being editted), and I was considering adding some kind of temporary save changes feature to the extension. 

If we would use the tiddlyfox extension, we could inject another script, and it would require knowing how each different version operates and attach the right handler, but maybe that is alright. What do you think? It could be fairly easy, I suppose.

**Comment by tobibeer** [comment] 2016-01-03 21:28
@Arlen22, perhaps skip any functionality beyond basic saving (for now)? Not exactly sure for what case any custom / additional "are you sure" type handling is needed, since TiddlyWiki aleady does save drafts as tiddlers. What (type of process / handling) did you have in mind?

Would be nice to not need any additional plugin module.

**Comment by Arlen22** [comment] 2016-01-04 21:47
@tobibeer, Will TiddlyFox actually save that draft to the file system immediately? If so, then that should be all we need.

**Comment by tobibeer** [comment] 2016-01-04 22:57
@Arlen22, I think **TiddlyWiki** does... and so TiddlyFox as an implementation of a saver module does ...as it is told to ...e.g. "save drafts as well".

**Comment by Jermolene** [comment] 2016-01-04 23:12
There may be some confusion here. Using a saver module saves the entire standalone HTML file; drafts are included, but saves are not triggered until 'confirm' is clicked after editing a tiddler. Using the client-server configuration syncs all changes to individual tiddlers directly to the file system; drafts are saved continuously as they are saved.

**Comment by Arlen22** [comment] 2016-01-05 03:08
Ok, that's what I was thinking. Thus the need to have something to actually save unsaved changes to the filesystem. But actually, using the tiddlyfox saver plugin that is already in TW5 isn't really held back by this anyway. The problem still exists, but its a separate problem.

**Comment by tobibeer** [comment] 2016-01-05 08:13
@Jermolene: Not sure I understand what this means:

> drafts are included, but saves are not triggered until 'confirm' is clicked after editing a tiddler

When does a user have to additionally confirm something / how to reproduce?

**Comment by Jermolene** [comment] 2016-01-05 08:44
The 'confirm' button is the tick icon that you click to complete editing a tiddler. In the code it's called the 'save' button but we switched the docs some time ago to avoid confusion with the save changes button.

**Comment by tobibeer** [comment] 2016-01-05 09:49
Ah, ok... I was wondering when there would be a js confirm popping up.

**Comment by Jermolene** [comment] 2016-01-05 10:46
Sorry @tobibeer I think you are misunderstanding. This is not about JavaScript confirm dialogues. This is about how when editing a tiddler an autosave (for compatible savers) is only triggered when clicking the "tick" icon, which used to be called "save" and is now called "confirm".

**Comment by tobibeer** [comment] 2016-01-05 10:49
Yes, I understood. :-)

**Comment by Jermolene** [comment] 2016-01-05 10:50
What did you mean about the js confirm popping up?

**Comment by tobibeer** [comment] 2016-01-05 10:52
That — before your explanation — I was wondering what confirm you might be referring to... and only then I realized you are not talking about js at all. :-)

**Comment by Arlen22** [comment] 2016-04-22 13:05
The TiddlyChromeSaver is no longer used.

**Closed as completed** 2016-04-22 13:05 UTC
